In [2]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv("Social Media Engagement Dataset.csv")

In [4]:
df

,post_id,timestamp,day_of_week,platform,user_id,location,language,text_content,hashtags,mentions,...,comments_count,impressions,engagement_rate,brand_name,product_name,campaign_name,campaign_phase,user_past_sentiment_avg,user_engagement_growth,buzz_change_rate
0,kcqbs6hxybia,2024-12-09 11:26:15,Monday,Instagram,user_52nwb0a6,"Melbourne, Australia",pt,Just tried the Chromebook from Google. Best pu...,#Food,NaN,...,701,18991,0.19319,Google,Chromebook,BlackFriday,Launch,0.0953,-0.3672,19.1
1,vkmervg4ioos,2024-07-28 19:59:26,Sunday,Twitter,user_ucryct98,"Tokyo, Japan",ru,Just saw an ad for Microsoft Surface Laptop du...,"#MustHave, #Food","@CustomerService, @BrandCEO",...,359,52764,0.05086,Microsoft,Surface Laptop,PowerRelease,Post-Launch,0.1369,-0.4510,-42.6
2,memhx4o1x6yu,2024-11-23 14:00:12,Saturday,Reddit,user_7rrev126,"Beijing, China",ru,What's your opinion about Nike's Epic React? ...,"#Promo, #Food, #Trending",NaN,...,643,8887,0.45425,Nike,Epic React,BlackFriday,Post-Launch,0.2855,-0.4112,17.4
3,bhyo6piijqt9,2024-09-16 04:35:25,Monday,YouTube,user_4mxuq0ax,"Lagos, Nigeria",en,Bummed out with my new Diet Pepsi from Pepsi! ...,"#Reviews, #Sustainable","@StyleGuide, @BrandSupport",...,743,6696,0.42293,Pepsi,Diet Pepsi,LaunchWave,Launch,-0.2094,-0.0167,-5.5
4,c9dkiomowakt,2024-09-05 21:03:01,Thursday,Twitter,user_l1vpox2k,"Berlin, Germany",hi,Just tried the Corolla from Toyota. Absolutely...,"#Health, #Travel","@BrandSupport, @InfluencerName",...,703,47315,0.08773,Toyota,Corolla,LocalTouchpoints,Launch,0.6867,0.0807,38.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,vpqni584supc,2025-01-10 07:55:51,Friday,Instagram,user_ysobum87,"Seoul, South Korea",ar,Comparing Toyota Camry to the competition. Bes...,"#Food, #BestValue","@IndustryExpert, @InfluencerName",...,41,220,22.08636,Toyota,Camry,CustomerFirst,Pre-Launch,-0.0299,0.0205,-6.0
11996,h8rvov0xym5z,2024-12-04 18:50:38,Wednesday,Reddit,user_2jzngfsp,"New York, USA",pt,My two days review of Apple AirPods Pro: Highl...,#TrendAlert,"@TrendSetter, @NewsOutlet",...,176,17346,0.20546,Apple,AirPods Pro,FallCollection,Launch,0.5936,-0.0928,-92.1
11997,14zrjm51ea3y,2024-10-24 19:11:24,Thursday,Facebook,user_0sidyfyh,"Lyon, France",ja,Just unboxed my new Dri-FIT from Nike. Best pu...,#Food,"@RetailSupport, @TechHelp",...,330,90913,0.05342,Nike,Dri-FIT,LocalTouchpoints,Post-Launch,0.0899,-0.1186,-96.8
11998,7bdmnv3rdj8n,2024-11-12 03:07:19,Tuesday,Reddit,user_njyhr041,"Manchester, UK",fr,Comparing Toyota Camry to the competition. Doe...,"#SpecialOffer, #Promo, #Fashion","@BrandSupport, @TechHelp",...,221,78790,0.04732,Toyota,Camry,CyberMonday,Post-Launch,-0.3666,-0.4527,15.9
11999,28cbflmapxbj,2024-05-15 20:07:23,Wednesday,Reddit,user_gbxy87di,"Tokyo, Japan",zh,Just saw an ad for Apple iMac during the Innov...,"#Sale, #Fitness",@MarketingTeam,...,420,80440,0.01828,Apple,iMac,SpringBlast2025,Launch,0.3128,0.3859,-23.5

In [5]:
df.shape

(12000, 28)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 28 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   post_id                  12000 non-null  str
 1   timestamp                12000 non-null  str
 2   day_of_week              12000 non-null  str
 3   platform                 12000 non-null  str
 4   user_id                  12000 non-null  str
 5   location                 12000 non-null  str
 6   language                 12000 non-null  str
 7   text_content             12000 non-null  str
 8   hashtags                 12000 non-null  str
 9   mentions                 8059 non-null   str
 10  keywords                 12000 non-null  str
 11  topic_category           12000 non-null  str
 12  sentiment_score          12000 non-null  float64
 13  sentiment_label          12000 non-null  str
 14  emotion_type             12000 non-null  str
 15  toxicity_score           12000 non-null  float64
 16  likes_count              12000 non-null  int64
 17  shares_count             12000 non-null  int64
 18  comments_count           12000 non-null  int64
 19  impressions              12000 non-null  int64
 20  engagement_rate          12000 non-null  float64
 21  brand_name               12000 non-null  str
 22  product_name             12000 non-null  str
 23  campaign_name            12000 non-null  str
 24  campaign_phase           12000 non-null  str
 25  user_past_sentiment_avg  12000 non-null  float64
 26  user_engagement_growth   12000 non-null  float64
 27  buzz_change_rate         12000 non-null  float64
dtypes: float64(6), int64(4), str(18)
memory usage: 6.2 MB

In [7]:
df.isnull().sum()

post_id                       0
timestamp                     0
day_of_week                   0
platform                      0
user_id                       0
location                      0
language                      0
text_content                  0
hashtags                      0
mentions                   3941
keywords                      0
topic_category                0
sentiment_score               0
sentiment_label               0
emotion_type                  0
toxicity_score                0
likes_count                   0
shares_count                  0
comments_count                0
impressions                   0
engagement_rate               0
brand_name                    0
product_name                  0
campaign_name                 0
campaign_phase                0
user_past_sentiment_avg       0
user_engagement_growth        0
buzz_change_rate              0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.head()

,post_id,timestamp,day_of_week,platform,user_id,location,language,text_content,hashtags,mentions,...,comments_count,impressions,engagement_rate,brand_name,product_name,campaign_name,campaign_phase,user_past_sentiment_avg,user_engagement_growth,buzz_change_rate
0,kcqbs6hxybia,2024-12-09 11:26:15,Monday,Instagram,user_52nwb0a6,"Melbourne, Australia",pt,Just tried the Chromebook from Google. Best pu...,#Food,NaN,...,701,18991,0.19319,Google,Chromebook,BlackFriday,Launch,0.0953,-0.3672,19.1
1,vkmervg4ioos,2024-07-28 19:59:26,Sunday,Twitter,user_ucryct98,"Tokyo, Japan",ru,Just saw an ad for Microsoft Surface Laptop du...,"#MustHave, #Food","@CustomerService, @BrandCEO",...,359,52764,0.05086,Microsoft,Surface Laptop,PowerRelease,Post-Launch,0.1369,-0.4510,-42.6
2,memhx4o1x6yu,2024-11-23 14:00:12,Saturday,Reddit,user_7rrev126,"Beijing, China",ru,What's your opinion about Nike's Epic React? ...,"#Promo, #Food, #Trending",NaN,...,643,8887,0.45425,Nike,Epic React,BlackFriday,Post-Launch,0.2855,-0.4112,17.4
3,bhyo6piijqt9,2024-09-16 04:35:25,Monday,YouTube,user_4mxuq0ax,"Lagos, Nigeria",en,Bummed out with my new Diet Pepsi from Pepsi! ...,"#Reviews, #Sustainable","@StyleGuide, @BrandSupport",...,743,6696,0.42293,Pepsi,Diet Pepsi,LaunchWave,Launch,-0.2094,-0.0167,-5.5
4,c9dkiomowakt,2024-09-05 21:03:01,Thursday,Twitter,user_l1vpox2k,"Berlin, Germany",hi,Just tried the Corolla from Toyota. Absolutely...,"#Health, #Travel","@BrandSupport, @InfluencerName",...,703,47315,0.08773,Toyota,Corolla,LocalTouchpoints,Launch,0.6867,0.0807,38.8

In [10]:
df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')

In [11]:
df.isnull().sum()

post_id                       0
timestamp                     0
day_of_week                   0
platform                      0
user_id                       0
location                      0
language                      0
text_content                  0
hashtags                      0
mentions                   3941
keywords                      0
topic_category                0
sentiment_score               0
sentiment_label               0
emotion_type                  0
toxicity_score                0
likes_count                   0
shares_count                  0
comments_count                0
impressions                   0
engagement_rate               0
brand_name                    0
product_name                  0
campaign_name                 0
campaign_phase                0
user_past_sentiment_avg       0
user_engagement_growth        0
buzz_change_rate              0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df['timestamp'].dtype

dtype('<M8[us]')

In [14]:
df['mentions'].head(10)

0                                NaN
1        @CustomerService, @BrandCEO
2                                NaN
3         @StyleGuide, @BrandSupport
4     @BrandSupport, @InfluencerName
5                                NaN
6                                NaN
7    @MarketingTeam, @InfluencerName
8                       @TrendSetter
9                      @BrandSupport
Name: mentions, dtype: str

In [15]:
df['mentions'].value_counts(dropna=False).head(10)

mentions
NaN                 3941
@RetailSupport       286
@BrandCEO            285
@InfluencerName      284
@CompetitorBrand     281
@IndustryExpert      277
@CelebrityName       275
@ProductTeam         270
@CustomerService     268
@MarketingTeam       266
Name: count, dtype: int64

In [16]:
print(df.duplicated().sum())
print(df['timestamp'].dtype)
print(df['mentions'].head(10))
print(df['mentions'].value_counts(dropna=False).head(10))

0
datetime64[us]
0                                NaN
1        @CustomerService, @BrandCEO
2                                NaN
3         @StyleGuide, @BrandSupport
4     @BrandSupport, @InfluencerName
5                                NaN
6                                NaN
7    @MarketingTeam, @InfluencerName
8                       @TrendSetter
9                      @BrandSupport
Name: mentions, dtype: str
mentions
NaN                 3941
@RetailSupport       286
@BrandCEO            285
@InfluencerName      284
@CompetitorBrand     281
@IndustryExpert      277
@CelebrityName       275
@ProductTeam         270
@CustomerService     268
@MarketingTeam       266
Name: count, dtype: int64

In [17]:
df['mentions'] = df['mentions'].fillna('No Mention')

In [18]:
df['total_engagements'] = df['likes_count'] + df['comments_count'] + df['shares_count']

In [19]:
df['posting_hour'] = df['timestamp'].dt.hour

In [20]:
df['posting_month'] = df['timestamp'].dt.month

In [21]:
def get_time_bucket(hour):
    if 5 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 21:
        return 'Evening'
    else:
        return 'Night'

In [22]:
df['mentions'] = df['mentions'].fillna('No Mention')

df['total_engagement'] = df['likes_count'] + df['shares_count'] + df['comments_count']

df['posting_hour'] = df['timestamp'].dt.hour
df['posting_month'] = df['timestamp'].dt.month

def get_time_bucket(hour):
    if 5 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 21:
        return 'Evening'
    else:
        return 'Night'

df['posting_time_bucket'] = df['posting_hour'].apply(get_time_bucket)

print(df[['timestamp', 'posting_hour', 'posting_month', 'posting_time_bucket', 'total_engagement']].head())

            timestamp  posting_hour  posting_month posting_time_bucket  \
0 2024-12-09 11:26:15            11             12             Morning
1 2024-07-28 19:59:26            19              7             Evening
2 2024-11-23 14:00:12            14             11           Afternoon
3 2024-09-16 04:35:25             4              9               Night
4 2024-09-05 21:03:01            21              9               Night

   total_engagement
0              3669
1              2684
2              4037
3              2832
4              4151

In [23]:
print(df['mentions'].isnull().sum())
print(df['posting_time_bucket'].value_counts())
print(df[['total_engagement', 'posting_hour', 'posting_month']].head())

0
posting_time_bucket
Night        4088
Morning      3442
Afternoon    2468
Evening      2002
Name: count, dtype: int64
   total_engagement  posting_hour  posting_month
0              3669            11             12
1              2684            19              7
2              4037            14             11
3              2832             4              9
4              4151            21              9

In [24]:
def get_sentiment_bucket(score):
    if score > -0.6:
        return 'Strong Negative'
    elif score > -0.2:
        return 'Negative'
    elif score > 0.2:
        return 'Neutral'
    elif score > 0.6:
        return 'Positive'
    else:
        return "Strong Positive"
df['sentiment_bucket'] = df['sentiment_score'].apply(get_sentiment_bucket)

In [25]:
def get_toxicity_flag(score):
    if score >= 0.75:
        return 'High Risk'
    elif score >= 0.4:
        return 'Moderate Risk'
    else:
        return 'Low Risk'
df['toxicity_flag'] = df['toxicity_score'].apply(get_toxicity_flag)

In [26]:
df['engagement_per_1000_impressions'] = (df['total_engagement'] / df['impressions']) * 1000

In [27]:
def get_sentiment_bucket(score):
    if score <= -0.6:
        return 'Strong Negative'
    elif score <= -0.2:
        return 'Negative'
    elif score < 0.2:
        return 'Neutral'
    elif score < 0.6:
        return 'Positive'
    else:
        return 'Strong Positive'

df['sentiment_bucket'] = df['sentiment_score'].apply(get_sentiment_bucket)

def get_toxicity_flag(score):
    if score >= 0.75:
        return 'High Risk'
    elif score >= 0.4:
        return 'Medium Risk'
    else:
        return 'Low Risk'

df['toxicity_flag'] = df['toxicity_score'].apply(get_toxicity_flag)

df['engagement_per_1000_impressions'] = (df['total_engagement'] / df['impressions']) * 1000

print(df[['sentiment_score', 'sentiment_bucket', 'toxicity_score', 'toxicity_flag', 'engagement_per_1000_impressions']].head())

   sentiment_score sentiment_bucket  toxicity_score toxicity_flag  \
0           0.9826  Strong Positive          0.0376      Low Risk
1          -0.3793         Negative          0.9715     High Risk
2          -0.3596         Negative          0.5124   Medium Risk
3          -0.7282  Strong Negative          0.4002   Medium Risk
4           0.5460         Positive          0.0862      Low Risk

   engagement_per_1000_impressions
0                       193.196777
1                        50.868016
2                       454.259030
3                       422.939068
4                        87.731163

In [28]:
print(df['sentiment_bucket'].value_counts())
print(df['toxicity_flag'].value_counts())
print(df['engagement_per_1000_impressions'].describe())

sentiment_bucket
Strong Positive    2454
Strong Negative    2431
Negative           2423
Positive           2385
Neutral            2307
Name: count, dtype: int64
toxicity_flag
Low Risk       4768
Medium Risk    4141
High Risk      3091
Name: count, dtype: int64
count    12000.000000
mean       278.142141
std       1149.205535
min          1.889612
25%         49.105149
50%         80.612934
75%        163.129964
max      32211.711712
Name: engagement_per_1000_impressions, dtype: float64

In [29]:
df['virality_score'] = (
    df['shares_count'] * 0.5 + 
    df['comments_count'] * 0.3 + 
    df['likes_count'] * 0.2
)
engagement_median = df['engagement_per_1000_impressions'].median()
print(engagement_median)
def get_engagement_quality(score):
    if score >= engagement_median:
        return 'High Quality Engagement'
    else:
        return 'Low Quality Engagement'

df['engagement_quality_flag'] = df['engagement_per_1000_impressions'].apply(get_engagement_quality)
print(df[['likes_count', 'shares_count', 'comments_count', 'virality_score', 'engagement_quality_flag']].head())
print(df['engagement_quality_flag'].value_counts())
print(df['virality_score'].describe())

80.61293449026367
   likes_count  shares_count  comments_count  virality_score  \
0         1264          1704             701          1315.1
1          522          1803             359          1113.6
2         2689           705             643          1083.2
3         1827           262             743           719.3
4         2005          1443             703          1333.4

   engagement_quality_flag
0  High Quality Engagement
1   Low Quality Engagement
2  High Quality Engagement
3  High Quality Engagement
4  High Quality Engagement
engagement_quality_flag
High Quality Engagement    6000
Low Quality Engagement     6000
Name: count, dtype: int64
count    12000.000000
mean      1153.031358
std        418.712258
min         38.700000
25%        855.575000
50%       1153.600000
75%       1452.925000
max       2271.100000
Name: virality_score, dtype: float64

In [30]:
df.to_excel("cleaned_social_media_engagement.xlsx", index=False)